### PR TITLE
feat:  solace add per operation fields

### PR DESCRIPTION
**Pull request by GreenRover**
**Description**

- fix up solace bindings having a invalid schema
- feat: add per operation fields from: https://github.com/asyncapi/bindings/pull/237

**fix up solace bindings having a invalid schema**
To reproduce the bug, use this schema:
```yaml
components:
  schemas:
    Person:
      type: string        
  messages:
    PersonEvent:
      payload:
        $ref: '#/components/schemas/Person'
      schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
      contentType: application/json
operations:
  addPerson:
    action: send
    channel:
      $ref: '#/channels/address'
    messages:
      - $ref: '#/channels/address/messages/personEvent'
    bindings:
      solace:
        bindingVersion: 0.3.0
        destinations:
          - destinationType: queue
            queue:
              name: CreatedHREvents
              topicSubscriptions:
                - person/*/created
          - destinationType: queue
            queue:
              name: UpdatedHREvents
              topicSubscriptions:
                - person/*/updated
channels:
  person:
    address: person/{personId}/{eventType}
    parameters:
      personId:
        schema:
          type: string
      eventType:
        schema:
          type: string
    messages:
      personEvent:
        $ref: '#/components/messages/PersonEvent'
asyncapi: 3.0.0
info:
  title: HRApp
  version: 0.0.1
```

with: https://studio.asyncapi.com/

### CODE REVIEW

**Review by smoya — APPROVED** [review]
LGTM!

**Review by CameronRushton — APPROVED** [review]
Thanks again!

**Pull request merged**
