### PR TITLE
fix: kafka bindings not using latest version

### PR DESCRIPTION
**Pull request by dalelane**
cf. spotted in a comment in
https://github.com/asyncapi/spec-json-schemas/pull/481

### CODE REVIEW

**Review by derberg — APPROVED** [review]
Thanks

**Comment by ctasada** [comment]
@dalelane could it be that the `0.5.0` version is missing at https://github.com/asyncapi/spec-json-schemas/blame/bee34d8569a18ee2117b4f2b0529a4e883e73638/definitions/3.0.0/serverBindingsObject.json#L53 too?

We're trying to upgrade Springwolf-asyncapi to support Kafka 0.5.0 bindings, but the cli parser complains with an error about unsupported version.

**Comment by jonaslagoni** [comment]
@ctasada yep, mind opening a PR?

**Comment by ctasada** [comment]
@jonaslagoni I created https://github.com/asyncapi/spec-json-schemas/pull/508 

Looking forward for your feedback

**Pull request merged**
