### PR TITLE
feat: add host and pathname fields in server object

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Add `host` and `pathname` fields in server object.

**Related issue(s)**
Part of https://github.com/asyncapi/spec/pull/888

### CODE REVIEW

**Review by fmvilas — APPROVED** [review]

**Review by char0n — APPROVED** [review]
LGTM. Nice job!

**Comment by magicmatatjahu** [comment]
@fmvilas @char0n Thanks! However I think that we should add some regex (or format) to validate the proper host and pathname, not treat fields as normal strings. WDYT? The problem is that I will (probably) learn Regex again 😆

**Comment by char0n** [comment]
@magicmatatjahu we theoretically can, here are the representation in pseudo context-free grammar for host and pathname.

**host**:
```
host:
      ‘[‘ ipv6-address ‘]’
      ipv4-or-reg-name

ipv6-address:
      (any input-character except ‘/’ and ‘]’)+
ipv4-or-reg-name:
      (any input-character except ‘/’, ‘:’, ‘?’ and ‘#’)+
```

**pathname**

As far as I understand this is https://url.spec.whatwg.org/#dom-url-pathname without `search` part

```
absolute-path:
      ‘/’
      (path-separator segment)+

path-separator:
      ‘/’
      new-line-with-indent

segment:
      (any input-character except ‘/’, ‘?’ and ‘#’)*
```

It should be possible to convert these context-free grammars into regular expressions.

**Review by dalelane — APPROVED** [review]

**Comment by fmvilas** [comment]
> @fmvilas @char0n Thanks! However I think that we should add some regex (or format) to validate the proper host and pathname, not treat fields as normal strings. WDYT? The problem is that I will (probably) learn Regex again 😆

I would create another issue for this. This is the kind of task that can quickly become a rabbithole.

**Comment by magicmatatjahu** [comment]
@fmvilas Ok, I created issue https://github.com/asyncapi/spec-json-schemas/issues/336 I'm merging that PR.

**Pull request merged**
