### PR TITLE
feat: update next major spec with master

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR updates the `next_major_spec` branch with master commits

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Important that you merge this PR as `merge commit` and not a `squash commit`, this means you have to change some settings in the repo most likely!

Otherwise, the merge conflicts will come back to haunt us later on 😄 

cc codeowners @fmvilas @whitlockjc @derberg @dalelane @smoya

**Comment by fmvilas** [comment]
Shouldn't this PR point to `next-major-spec` branch? 🤔

**Comment by jonaslagoni** [comment]
Of course @fmvilas 🤦 Changing.

**Review by fmvilas — DISMISSED** [review]
I'm happy to merge manually with a merge commit. Let's wait for the others to see what they have to say.

**Review by dalelane — DISMISSED** [review]

**Review by derberg — APPROVED** [review]

**Comment by jonaslagoni** [comment]
Updated with the latest master changes.

**Comment by fmvilas** [comment]
@dalelane @derberg please approve again 🙏

**Review by dalelane — APPROVED** [review]

**Review by derberg — APPROVED** [review]

**Review by fmvilas — APPROVED** [review]

**Comment by fmvilas** [comment]
Alright, merged with merge commit @jonaslagoni

**Pull request merged**
