### PR TITLE
feat: added schema for 2.2.0 based on 2.1.0 and added anypointmq protocol

### PR DESCRIPTION
**Pull request by GeraldLoeffler**
**Description**

- new JSON Schema document for 2.2.0 created by simply copying that for 2.1.0 and updating mentions of `2.1.0` to `2.2.0`
- added `anypointmq` protocol as per https://github.com/asyncapi/spec/issues/514

**Related issue(s)**

- See https://github.com/asyncapi/spec/issues/514

### CODE REVIEW

**Comment by GeraldLoeffler** [comment]
@derberg : i've commited the 2.2.0 schema, but for whatever reason 6 more files (such as .github/workflows/automerge-orphans.yml) are listed in this PR: i did not touch those. What should i do?

**Comment by derberg** [comment]
hey, I think you created a branch in your fork from latest master and not the release branch and in this PR, instead of just changes in the schema, you introduce other changes that were in master but not in release branch. Can you revert that? so changes here are only about the json schema?

**Comment by GeraldLoeffler** [comment]
you might be right @derberg , how embarrassing. I've cleaned this up now.

**Comment by derberg** [comment]
@GeraldLoeffler no worries. All looks good from my side if it comes to the schema, I checked with external diff checker. You need to just add new schema here https://github.com/asyncapi/spec-json-schemas/blob/2021-09-release/index.js, this is why tests are failing

Screenshot 2021-09-15 at 16 36 40
Screenshot 2021-09-15 at 16 36 59

**Review by derberg — APPROVED** [review]
lgtm 🚀 

@fmvilas anything from your side?

**Review by fmvilas — APPROVED** [review]
Nope, ship it!

**Pull request merged**
