### PR TITLE
feat: add OpenAPI 3.0 Schema 

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
As done in https://github.com/asyncapi/spec-json-schemas/pull/348 this PR adds the OpenAPI 3.0 Schema object for all v2 versions.

It is quite a few duplicate schemas... But there is currently no setup to share schemas between versions... Would be great to have at some point. See https://github.com/asyncapi/spec-json-schemas/issues/364

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
is there anything needed on the script that creates new definitions for new version

@fmvilas have a look, I think it is good direction, except of my fear against `if/then`

**Comment by jonaslagoni** [comment]
>is there anything needed on the script that creates new definitions for new version

@derberg Nope there should not 🙂

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Comment by derberg** [comment]
after merging https://github.com/asyncapi/spec-json-schemas/pull/363 you have some conflicts to solve

**Comment by jonaslagoni** [comment]
@derberg LGTM 👍  Thanks for taking care of this!

**Review by derberg — APPROVED** [review]

**Pull request merged**
