### PR TITLE
docs: update operationTrait.json

### PR DESCRIPTION
**Pull request by SuryaPratap1008**
**Description**

OperationTrait.json has been successfully updated by mentioning the message inside the object description as being excluded
async

**Related issue(s)**
fixes #994

### CODE REVIEW

**Review by smoya — DISMISSED** [review]
LGTM! 🚀🌔

**Review by smoya — CHANGES_REQUESTED** [review]
@SuryaPratap1008 Please change the base branch to `master`.

**Review by mboss37 — APPROVED** [review]

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Pull request merged**
