### PR TITLE
fix: enable `$ref` support for bindings

### PR DESCRIPTION
**Pull request by derberg**
fixes: https://github.com/asyncapi/spec-json-schemas/issues/438

tested locally following https://github.com/asyncapi/spec-json-schemas/#schemastore-compatibility-testing and works like a charm

### CODE REVIEW

**Review by dalelane — APPROVED** [review]
LGTM

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Review by char0n — APPROVED** [review]
LGTM

**Pull request merged**
