### PR TITLE
feat: add reusable tags and externalDocs objects

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- add reusable Tags and External Documentation objects in the Components object
- add Tags and External Documentation objects in missed places - part of https://github.com/asyncapi/spec/pull/796

Spec PR https://github.com/asyncapi/spec/pull/792

**Related issue(s)**
Part of https://github.com/asyncapi/spec/pull/792
Part of https://github.com/asyncapi/spec/pull/796

### CODE REVIEW

**Review by dalelane — APPROVED** [review]

**Review by fmvilas — APPROVED** [review]

**Review by derberg — DISMISSED** [review]

**Comment by derberg** [comment]
please do not merge yet because of https://github.com/asyncapi/spec-json-schemas/pull/264#issuecomment-1273027917

/dnm

**Comment by magicmatatjahu** [comment]
@derberg @fmvilas @char0n @dalelane @smoya Someone from you could check that? Thanks!

**Review by fmvilas — APPROVED** [review]

**Review by derberg — APPROVED** [review]

**Pull request merged**
