### PR TITLE
feat!: remove duplicate schemas

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
Even though we enabled the reusability of schemas in https://github.com/asyncapi/spec-json-schemas/issues/364, the documents were never adapted, leaving a lot of unnecessary documents. This removes those and uses the common definitions.

This means there will no longer be anything called `http://asyncapi.com/definitions/x.x.x/avroSchema_v1.json` or `http://asyncapi.com/definitions/x.x.x/openapiSchema_3_0.json` but only `http://asyncapi.com/common/avroSchema_v1.json` and `http://asyncapi.com/common/openapiSchema_3_0.json`

**Related issue(s)**
Should have been fixed as part of https://github.com/asyncapi/spec-json-schemas/issues/364

### CODE REVIEW

**Comment by jonaslagoni** [comment]
I see the bundler has some custom code for common, have to redefine that.

**Comment by jonaslagoni** [comment]
Think we have to move this over to a `next` release branch

**Review by Pakisan — APPROVED** [review]
Looks valid for me

**Review by Pakisan — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@dalelane @lbroudoux because of the Kafka binding change Github need one of you to take a look when you can 🤙

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Review by smoya — CHANGES_REQUESTED** [review]
@jonaslagoni Not a good deal to have the need of serving those common schemas under the path `common` on the root of `http://asyncapi.com`. Not only because the need of adding an extra redirection but also because it is requiring a new path `/common` that is not so intuitive in terms of naming (what is common in relation to the AsyncAPI website?).

WDYT about `http://asyncapi.com/schemas/common`? This will require a move of the `common` dir under `schemas` directory.

**Comment by jonaslagoni** [comment]
> @jonaslagoni Not a good deal to have the need of serving those common schemas under the path `common` on the root of `http://asyncapi.com`. Not only because the need of adding an extra redirection but also because it is requiring a new path `/common` that is not so intuitive in terms of naming (what is common in relation to the AsyncAPI website?).
> 
> WDYT about `http://asyncapi.com/schemas/common`? This will require a move of the `common` dir under `schemas` directory.

Schemas hold the bundled versions, and think we should keep it clean like that 🤔 

What about under `definitions`?

**Comment by smoya** [comment]
> What about under `definitions`?

Fine with it.

**Comment by Pakisan** [comment]
@jonaslagoni @smoya maybe repeat structure from jasyncapi?

Current tests, which I'm writing now, in other branch, were grouped by next logic

- models/[v2|v3]
- schemas/[openapi|asyncapi|avro|json]
- /schemas/asyncapi/security schemas/[v2|v3]/{security implementation}

They could be unified for all versions, but in v3 version one property was renamed for OAuth2 flow 😣

**Comment by jonaslagoni** [comment]
> @jonaslagoni @smoya maybe repeat structure from jasyncapi?
> 
> Current tests, which I'm writing now, in other branch, were grouped by next logic
> 
>     * models/[v2|v3]
> 
>     * schemas/[openapi|asyncapi|avro|json]
> 
>     * /schemas/asyncapi/security schemas/[v2|v3]/{security implementation}
> 
> 
> They could be unified for all versions, but in v3 version one property was renamed for OAuth2 flow 😣

@Pakisan mind opening an issue for it? 🙂 It will for sure be lost in this PR 😅

**Review by dalelane — APPROVED** [review]

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Pull request merged**
