### PR TITLE
chore: update release branch

### PR DESCRIPTION
**Pull request by dalelane**
- create new version of json schema
- update release branch name in package.json

Contributes to: asyncapi/spec#675

Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>

### CODE REVIEW

**Comment by smoya** [comment]
The following PR is creating the new schema file https://github.com/asyncapi/spec-json-schemas/pull/133. 
So in case we merge it soon, we won't need to do `create new version of json schema`.

**Review by derberg — APPROVED** [review]
LGTM 🚀

@fmvilas have a look

**Review by fmvilas — APPROVED** [review]
:shipit:

**Pull request merged**
