### PR TITLE
feat: make server variables reuseable

### PR DESCRIPTION
**Pull request by danielkocot**
**Description**

Part of asyncapi/spec#717

This PR adds `serverVariables` as reusable objects to be used in `components`.

**Related issue(s)**
asyncapi/spec#717

### CODE REVIEW

**Comment by smoya** [comment]
For the record, here is the diff between `2.3.0.json` and `2.4.0.json` (introduced here):

```diff
--- schemas/2.3.0.json	2022-02-09 16:34:30.801505242 +0100
+++ /tmp/2.4.0.json	2022-02-16 12:50:09.386606793 +0100
@@ -1,5 +1,5 @@
 {
-  "title": "AsyncAPI 2.3.0 schema.",
+  "title": "AsyncAPI 2.4.0 schema.",
   "$schema": "http://json-schema.org/draft-07/schema#",
   "type": "object",
   "required": [
@@ -17,7 +17,7 @@
     "asyncapi": {
       "type": "string",
       "enum": [
-        "2.3.0"
+        "2.4.0"
       ],
       "description": "The AsyncAPI specification version of this document."
     },
@@ -270,6 +270,9 @@
         "servers": {
           "$ref": "#/definitions/servers"
         },
+        "serverVariables": {
+          "$ref": "#/definitions/serverVariables"
+        },
         "channels": {
           "$ref": "#/definitions/channels"
         },

```

**Review by smoya — COMMENTED** [review]
LGTM, However I'm not a Code Owner. 

I think we would need to create a new release branch for the next minor and point this PR to it.

Any thoughts? cc @fmvilas @derberg

**Review by fmvilas — APPROVED** [review]
LGTM 👍

**Comment by fmvilas** [comment]
Let's wait for @derberg and @dalelane review too.

**Review by dalelane — APPROVED** [review]
I think @smoya is right that we can't merge this into master as-is so we need to either park it for a bit, or switch the PR to target somewhere ready for the next release. 

But those git-logistics aside, this looks like a good idea to me

**Comment by derberg** [comment]
we need to find volunteer to run `2.4.0` release coordination 😓

**Comment by smoya** [comment]
@derberg we need a `next` branch so we can merge the code that will be released in `2.4.0`.

**Comment by smoya** [comment]
> we need to find volunteer to run `2.4.0` release coordination 😓

I volunteer 👍

**Comment by derberg** [comment]
> I volunteer 👍

oh, that was easy ❤️ 

branches created:
- https://github.com/asyncapi/spec/tree/2022-04-release
- https://github.com/asyncapi/spec-json-schemas/tree/2022-04-release
- https://github.com/asyncapi/parser-js/tree/2022-04-release

I highly recommend you start coordinating by opening an issue just like proposed by @dalelane in [this PR](https://github.com/asyncapi/spec/pull/722) and also using his updated release process instructions. I left few comments that but majority of the content is what should be followed

**Comment by smoya** [comment]
> > I volunteer 👍
> 
> oh, that was easy ❤️
> 
> branches created:
> 
> * https://github.com/asyncapi/spec/tree/2022-04-release
> * https://github.com/asyncapi/spec-json-schemas/tree/2022-04-release
> * https://github.com/asyncapi/parser-js/tree/2022-04-release
> 
> I highly recommend you start coordinating by opening an issue just like proposed by @dalelane in [this PR](https://github.com/asyncapi/spec/pull/722) and also using his updated release process instructions. I left few comments that but majority of the content is what should be followed

I thought we would finally follow semantic-release and instead use `next` branches for those releases.

**Comment by derberg** [comment]
> I thought we would finally follow semantic-release and instead use next branches (as we do for next-major) for those releases.
I suggested it in the past in Slack as well: https://asyncapi.slack.com/archives/C0230UAM6R3/p1644418043568169

well I remember the discussion about `next-major` but do not recall being involved in the discussion about spec release branches that are named after release cadence. I personally like the current names of release branches, they clearly indicate what you can expect + they make sense as you know when you release, while with `next` you clearly not. Anyway, if you want to change it you need to start open discussion as for now it is part of https://github.com/asyncapi/spec/blob/master/RELEASE_PROCESS.md and was agreed in a discussion about release cadence https://github.com/asyncapi/spec/issues/513. Just clear explain what are the benefits.

**Comment by smoya** [comment]
@danielkocot we have now the release branches for `2.4.0`. Would you mind changing the base branch to `2022-04-release` ? Thanks!

**Comment by derberg** [comment]
@smoya we still have it scheduled for April right?

**Comment by smoya** [comment]
> @smoya we still have it scheduled for April right?

Yes, we do. https://github.com/asyncapi/spec/issues/735

**Comment by smoya** [comment]
@danielkocot would you mind updating your branch with latest upstream changes? It seems there are some conflicts.

**Comment by smoya** [comment]
> I'm seeing a lot of changes in Markdown files. Is that expected? 🤔

I think for some reason, target branch didn't get updated with `master` branch changes, and those changes introduced in https://github.com/asyncapi/spec-json-schemas/pull/174/commits/7e9a2a38883fa5ce131bd7064fd373f3e09c4507 are not in there. 
Will see what is happening.

**Review by derberg — APPROVED** [review]
all good but I see some conflicts there that will block merging

**Comment by smoya** [comment]
@danielkocot We are almost there! Only one thing pending: would you mind fixing the merge conflicts? After you do it, the owners will merge it.

**Pull request merged**
