### PR TITLE
feat: re-trigger message payload validation

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR re-triggers the release workflow as it failed the last time https://github.com/asyncapi/spec-json-schemas/pull/334

### CODE REVIEW

**Comment by smoya** [comment]
For more context: The action keeps failing since the merged commit didn't have the fix for increasing the timeout on the test (the actual error). This PR is up-to-date and contains such a change.

**Comment by smoya** [comment]
@jonaslagoni can you just do `git commit --alow-empty` instead of adding that empty line?

**Comment by derberg** [comment]
I don't think we need it, I'm rerunning the initial release. MacOS just went through, waiting for Windows

**Comment by smoya** [comment]
> I don't think we need it, I'm rerunning the initial release. MacOS just went through, waiting for Windows

LOL! The previous re-run I made was also failing. Now it seems it doesn't. 

good-luck-salute-gif

**Comment by derberg** [comment]
yeah, call me `re-run ninja`

**Comment by derberg** [comment]
oh yeah, after all you need to merge this as release was not triggered as in the meantime you merged PR with timeout increase 🤷🏼

**Comment by jonaslagoni** [comment]
Yea 😄

**Comment by jonaslagoni** [comment]
@smoya done 🙂

**Review by smoya — APPROVED** [review]

**Pull request merged**
