### PR TITLE
chore: update next-spec branch with master changes

### PR DESCRIPTION
**Pull request by char0n**
This is PR is part of https://github.com/asyncapi/spec/issues/830 and updates `next-spec` branch with changes from `master`.

### CODE REVIEW

**Comment by char0n** [comment]
@fmvilas @derberg @dalelane would you mind reviewing this PR please? Thanks

Verification question - I've created this PR by merging master branch with next-spec and issuing a PR containing the merges + a merge commit. There are other ways to achieve the same. Is there any preference in how to achieve the goal of updating the next-spec branch from master? If yes please let me know.

**Review by derberg — APPROVED** [review]
@char0n we did not standardize the flow here. I would also just merge master into next.

I think we should consider having a workflow that will always keep next branches up to date with master, on a regular basis between releases. This can be automated with https://github.com/marketplace/actions/update-git-branch and means one manual step less.. Just put it as followup release process improvement actions after release.

**Comment by char0n** [comment]
> @char0n we did not standardize the flow here. I would also just merge master into next.

ACKN.

> I think we should consider having a workflow that will always keep next branches up to date with master, on a regular basis between releases. This can be automated with https://github.com/marketplace/actions/update-git-branch and means one manual step less.. Just put it as followup release process improvement actions after release.

Added in https://github.com/asyncapi/spec/issues/830

**Pull request merged**
