### PR TITLE
refactor: enable reusability of schemas between versions

### LINKED ISSUE #364: Enable reusability of schemas between versions
#### Reason/Context
There are specifically 2 schemas we wish to share among all versions.
- avroSchema_v1
- openapiSchema_3_0

To achieve this we need to do the following:
1. Move the common schemas to a common definition folder
2. Adapt the bundler (tools/bundler/index.js) to include these common definitions for all versions.

### PR DESCRIPTION
**Pull request by devilkiller-ag**
**Description**
Adding functionality to share these schemas to all versions:
- avroSchema_v1
- openapiSchema_3_0

**Related issue(s)**
Fixes #364

### CODE REVIEW

**Comment by devilkiller-ag** [comment]
This work is still in progress. I will update the `tools/bundler/index.js` soon to adapt these changes.

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, The IIFE in the `tools/bundler/index.js` uses `asyncapi.json` of every version as `fileToBundle`. Why it is used for? And since the common folder will not have such file, what should I use for `fileToBundle`. Or will I have to write different implementation for this folder?

**Comment by jonaslagoni** [comment]
> Hi @jonaslagoni, The IIFE in the `tools/bundler/index.js` uses `asyncapi.json` of every version as `fileToBundle`. Why is it used for?

It is the entry point for bundling, all references therein is being bundled recursively.

> And since the common folder will not have such a file, what should I use for fileToBundle? Or will I have to write a different implementation for this folder? I am sorry, I have a little blurry understanding of bundler and spec-json-schemas. Is there any resource which can help me to develop an understanding of this?

The only changes you would need is something along the lines of; create a function for loadingCommonSchemas, which loops over all the files in the common folder, and adds them to the bundler memory. Similar to how the bindings are added: https://github.com/asyncapi/spec-json-schemas/blob/287ed2846a764ac6ffce1d5034a9e3e47853a247/tools/bundler/index.js#L44

Thats it. The rest of the bundler code should function fine after that.

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni! Sorry for the delay. This PR is ready for review now!

**Comment by devilkiller-ag** [comment]
@jonaslagoni Any updates regarding this PR?

**Comment by jonaslagoni** [comment]
@devilkiller-ag you need to have the codeowners to look at it ✌️

**Comment by devilkiller-ag** [comment]
@jonaslagoni Got it✨

**Comment by devilkiller-ag** [comment]
Hi @derberg @fmvilas @smoya @dalelane @char0n, can you review this PR ✨

**Comment by devilkiller-ag** [comment]
Hi @smoya, Can you please review this PR again?

**Review by smoya — COMMENTED** [review]
LGTM! 🚀🌔

**Review by smoya — APPROVED** [review]

**Pull request merged**
