### PR TITLE
fix: add v2 suffix to Go module

### PR DESCRIPTION
**Pull request by smoya**
**Description**

This change will make the Go module compatible with Go semantic versioning.
As the tag it is >= v2, Go requires `v2` suffix in module name. See https://golang.org/ref/mod#major-version-suffixes

I also took this opportunity to add few lines in the `README.md` explaining how to install and use the Go package.

**Related issue(s)**
The issue is that users won't be able to import the module ever due to the following error:
> invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

### CODE REVIEW

**Comment by jonaslagoni** [comment]
What do you need to progress here @smoya?

**Comment by smoya** [comment]
THis is blocked by https://github.com/asyncapi/spec-json-schemas/issues/130

**Review by derberg — APPROVED** [review]

**Pull request merged**
