### PR TITLE
feat: update with master

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR updates `next-major-spec` with master.

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Remember to merge this as regular commit.

**Review by smoya — APPROVED** [review]

**Review by smoya — CHANGES_REQUESTED** [review]
Note: This should be merged with "Rebase and merge", otherwise the commits will be lost. 

Google Chrome_CvLgckjf@2x

@derberg how should we proceed since that method is disabled?

I mark this as "Request changes" to block the merge.

**Comment by smoya** [comment]
I think the best still is keeping a PR always opened from `next-major` to `master` and tell @asyncapi-bot to keep it up-to-date.
Right @derberg ?

**Comment by jonaslagoni** [comment]
Its not possible because of conflicts in package version. Have to happen manually.

**Comment by smoya** [comment]
> @smoya you will have to change the settings of the branch and then change it back 🙂 

I thought that wasnt allowed to me. But it is. So proceeding.
However, better to find a long term solution, if any. Will create an issue later to discuss about this.

> Its not possible because of conflicts in package version. Have to happen manually. 

Yeah, right. The never ending story.

**Comment by smoya** [comment]
@jonaslagoni 

I dont fully get why squash and merge works but Rebase doesnt. Do you believe there are conflicts? Can you rebase and push?

**Pull request merged**
