### PR TITLE
chore: add v3.0.0 schemas

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR adds the new schemas for v3.0.0 so we can start applying changes.

This PR also merges the changes from Master that have happened since the branch was created.

fixes https://github.com/asyncapi/spec-json-schemas/issues/175

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Should this live on it's own branch instead of next-major 🤔

**Comment by magicmatatjahu** [comment]
@jonaslagoni I guess `next-major` refers to the next (major) version of AsyncAPI, right? If yes, then it's ok.

**Comment by jonaslagoni** [comment]
I will re-target this for `next-spec-major` once created, as that is where it will live until 3.0 is released.

**Comment by KhudaDad414** [comment]
@jonaslagoni I have been thinking about moving bindings schemas here and saw that this branch can be a good place to add them if we want to have bindings schemas for 3.0.0 of course. Are there any plans on merging this so I can open a PR for bindings?

**Comment by jonaslagoni** [comment]
> @jonaslagoni I have been thinking about moving bindings schemas here and saw that this branch can be a good place to add them if we want to have bindings schemas for 3.0.0 of course. Are there any plans on merging this so I can open a PR for bindings?

Yep!

I will create the corresponding branches and changes Monday next week so we can start moving this along 🙂

**Comment by jonaslagoni** [comment]
Damn, when targeted branches are removed, remaining PRs are closed as well with no way to retarget them...

**Comment by derberg** [comment]
why would you remove `next-major` ?

**Comment by jonaslagoni** [comment]
@derberg bot did when I used `/rtm`

**Comment by jonaslagoni** [comment]
I cannot re-open my own PRs 🤨 Can you @derberg?

**Comment by jonaslagoni** [comment]
Thats a lot of conflicts for something so easy as running a single command... Gonna remake it.

**Pull request closed without merging**
